spring:
  profiles: local

database:
  credentials:
    host: ec2-3-215-41-107.compute-1.amazonaws.com
    port: 5432
    username: sqhbvrorhjuntf
    password: 3c150db5d02f7e795c547de305401f1f1df2338f14136a648a7ba9f575b493da
    database: dajvdq3pnd2jp1

server:
  port: 8080

